### ISSUE TITLE
With which printers does the plugin work?

### ISSUE THREAD

**Issue by Nastras** [SeydX/homebridge-printer#1]
Hello SeydX,
can you tell me for which printers the plugin should work all ? For all AirPlay printers or only HP ?

I tried it with a Lexmark C3224dw. For this I have entered the IP address in Config but after adding to HK is only the bridge from the plugin is displayed no switch or sensor.

If you have a tip would be cool?

Greetings Nastra

**Comment by SeydX** [comment]
Hello @Nastras 

you need to enter the **ipp** address of the printer.

You can easily find the address with the following app

https://apps.apple.com/de/app/discovery-dns-sd-browser/id305441017

Connect to your WIFI, open the App, click on **local** and look if your printer is shown in the list.

If yes, click on your printer and copy the ipp address AND path from your printer and put it in the config

**Comment by Nastras** [comment]
Thanks for the quick reply. I have now read the ipp address with the app and entered this in the config. It still shows me only the bridge without devices?

![D970FDF5-7402-4E51-BCD8-3826B957A385](https://user-images.githubusercontent.com/27686185/102690508-2e5cc200-4206-11eb-8b54-718051a2ffda.jpeg)
![A164CE13-2C70-4998-BECC-8FFDDBA47871](https://user-images.githubusercontent.com/27686185/102690509-30268580-4206-11eb-989a-33caebcd3625.jpeg)
![B30A50F9-8012-4406-B2BF-01CE828B73D7](https://user-images.githubusercontent.com/27686185/102690510-30268580-4206-11eb-8cb1-976c8c490002.jpeg)

**Comment by SeydX** [comment]
@Nastras 

ah it seems the example config in readme.md is wrong. 

It uses ``"devices": []`` instead of ``"printer": []`` 

Change devices to printer in config.json should fix it

**Comment by Nastras** [comment]
I die it but now i get this:

![EBB112C1-137E-448B-8D90-17B9B4B5FB84](https://user-images.githubusercontent.com/27686185/102690669-4c76f200-4207-11eb-8944-79ece750c96c.jpeg)

![F0DD001D-EE6F-4902-93FD-0F53737274F9](https://user-images.githubusercontent.com/27686185/102690677-5ef12b80-4207-11eb-80d1-208c58384f19.jpeg)

**Comment by SeydX** [comment]
@Nastras 

it seems that the ipp address/path is wrong

Is the path you entered in config from the app? Or from the example config?

You need to give the ipp path from YOUR printer. Check the above mentioned app. Open your printer and scroll down. The path should be listed there

**Comment by Nastras** [comment]
You were right the path was wrong. The address that is needed is the part after adminurl = xxxxxxxxxxxxxxx now it works.

adminurl = http://ET788C7710637D.local./#/Settings/Network/AirPrint

It even shows the cartridge levels which is nowhere in the plugin description. Cool work thanks!

But now I have a question after I get the 2 devices displayed.

Is it not possible to display all the data under the contact sensor so that only one device appears in Homekit?

For the display of whether the printer is online, but also a custom character would be enough what as text online or offline displays instead of a power switch?

What do you think?

**Comment by Nastras** [comment]
Good morning, here is an example of how it might look 😉?

![834EDB8E-1981-4CD1-BE04-B1481B1A419F](https://user-images.githubusercontent.com/27686185/102706015-46782400-428e-11eb-99be-992b59d1a510.jpeg)

**Comment by martinnock** [comment]
as I had to do some research for my printer, here's the outcome, which may help a few of you

HP LaserJet P1102w (quite old ...):
Address to be used is ipp://IP-ADDRRESS:631/ipp
