### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by steff38** [SeydX/homebridge-printer#11]
When the printer is off, homebridge/homekit shows that the printer is on and I get this error message:

}
[27.2.2021, 14:19:31] [PrinterPlatform] LaserJet: An error occured during getting state
[27.2.2021, 14:19:31] [PrinterPlatform] Error: getaddrinfo ENOTFOUND laserjet.local
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'laserjet.local'
}

Is there any possibility to solve it and show the correct status in homebridge/homekit?

config:

{
    "name": "PrinterPlatform",
    "debug": false,
    "printer": [
        {
            "name": "LaserJet",
            "address": "http://laserjet.local:631/hp/device/info_deviceStatus.html?tab=Home&menu=DevStatus",
            "polling": 10
        }
    ],
    "platform": "PrinterPlatform"
}

Thanks in advance.

BR, steff

**Comment by SeydX** [comment]
Thx i will fix it

**Comment by SeydX** [comment]
should be fixed with v1.0.3

**Comment by steff38** [comment]
It works, thx!!!
