### ISSUE TITLE
Contact Sensor

### ISSUE THREAD

**Issue by ashleymoat** [SeydX/homebridge-printer#7]
Contact sensor not working for me. I've read your Pull Request regarding this but not 100% what I need to do and how. Some tips would be really good on how I get this part working. Thanks

**Comment by fototeddy** [comment]
look in the switch.js file around line 101 I think and replace 

`let markerLevel = attributes['marker-levels'];`

with 
`let markerLevel = [attributes['marker-levels']];`

also around line 46 replace
` let markers = attributes['marker-names'];`

with

` let markers = [attributes['marker-names']];`

that should be everything in my pull request and made it working for me

**Comment by SeydX** [comment]
fixed in v1.0.1
