### ISSUE TITLE
Many errors on Homebridge's log after last update

### ISSUE THREAD

**Issue by Stef1972** [SeydX/homebridge-printer#9]
I'm receiving this message, around one every second, since last update:

[25/02/2021, 09:30:45] [homebridge-printer] This plugin generated a warning from the characteristic 'Filter Life Level': characteristic value expected float and received undefined. See https://git.io/JtMGR for more info.

Any Idea ?

**Comment by solbadguy2010** [comment]
![Screenshot 2021-02-25 142509](https://user-images.githubusercontent.com/30244171/109159959-80c1de00-7775-11eb-8d5b-32fcc07f9a06.png)

**Comment by ash123-germany** [comment]
Doesn't work with Epson ET-2550

**Comment by solbadguy2010** [comment]
> Doesn't work with Epson ET-2550

Du solltest eine detailiertere Fehlermeldung posten und ggf. ein separates Issue erstellen, wenn du nicht genau den gleichen Fehler hast wie ich.

**Comment by solbadguy2010** [comment]
Sieht gut aus. Guck dir auch mal die geschlossenen Issues an. Ich hatte ähnliche Probleme und mir hat wer geholfen. 

Hoobs solltest du aber loswerden und auf das offizielle Homebridge Image wechseln. Zu finden unter homebridge.io

**Comment by SeydX** [comment]
Can u post your config.json pls

**Comment by solbadguy2010** [comment]
Sure

        {
            "platform": "PrinterPlatform",
            "name": "PrinterPlatform",
            "debug": false,
            "printer": [
                {
                    "name": "HP Laserjet M277dw",
                    "address": "http://M277dw.local./hp/device/info_config_AirPrint.html?tab=Networking&menu=AirPrintStatus",
                    "manufacturer": "Hewlett-Packard",
                    "model": "Color LaserJet MFP M277dw",
                    "serialNumber": "VNB8J4W31P"
                },
                {
                    "name": "Dymo LabelWriter 450",
                    "address": "ipp://Mac-Mini.local:631/printers/DYMO_LabelWriter_450",
                    "manufacturer": "Dymo",
                    "model": "LabelWriter 450",
                    "serialNumber": "1516021750111"
                }
            ],
            "_bridge": {
                "username": "0E:5E:AB:D8:88:ED",
                "port": 59075
            }
        },

**Comment by SeydX** [comment]
@solbadguy2010 

can u add „polling“ into your config.json pls

i.e.

``"polling": 10``

**Comment by solbadguy2010** [comment]
Done. Plugin is working with and without the "polling". I only get my log spammed with this Hombridge 1.3.x messages as seen in my screenshot.
This is described here: https://github.com/homebridge/homebridge/wiki/Characteristic-Warnings

**Comment by SeydX** [comment]
Should be fixed with v1.0.2

**Comment by solbadguy2010** [comment]
It is. 
great job. Thank you very much!
